<a href="https://colab.research.google.com/github/vatsalgoyal44/SoC2k21/blob/main/NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **NumPy Arrays**

In [ ]:
my_list = [1,2,3]

In [ ]:
  import numpy as np


In [ ]:
arr = np.array(my_list)

In [ ]:
 arr

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5) 

array([0.29585409, 0.58251489, 0.38153198, 0.12410959, 0.46489793])

In [ ]:
np.random.rand(2,3)

array([[0.22122087, 0.73138192, 0.98236362],
       [0.7791798 , 0.73280084, 0.45947674]])

In [ ]:
np.random.randn(2)

array([1.1549591 , 0.62175373])

In [ ]:
np.random.randint(1,100)

16

In [ ]:
np.random.randint(1,100,2)

array([44, 68])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
ranarr

array([23,  9, 23, 16,  7, 11, 10, 27,  6, 49])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(4,4)

ValueError: ignored

In [ ]:
ranarr

array([23,  9, 23, 16,  7, 11, 10, 27,  6, 49])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.min()

6

In [ ]:
ranarr.argmin()

8

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10)

6

### NumPy Indexing and Selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[0]

0

In [ ]:
arr[5]

5

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:6]

In [ ]:
slice_of_arr[:] = 99

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 100

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])